### ISSUE TITLE
PyBay Website is not responsive

### ISSUE THREAD

**Issue by polkapolka** [pybay/PyBay#1]
The website does not adjust to readable proportions on different sized screens.

https://pagespeed.web.dev/analysis/https-pybay-org/ssvkfa7zv1?form_factor=mobile

**Comment by benbobyabraham** [comment]
Working on this issue#1

**Comment by benbobyabraham** [comment]
Submitted pull request, please verify @polkapolka

**Comment by polkapolka** [comment]
Yes! The one line has dramatically improved the mobile responsiveness. However, there are still a lot of errors. I would like you to continue knocking through the errors that are being generated here. Specifically improving the Accessibility score.

https://pagespeed.web.dev/analysis/https-pybay-org/ssvkfa7zv1?form_factor=mobile

**Comment by benbobyabraham** [comment]
Sure, will check that out. Was unable to run the test on the codespaces test server.

**Comment by polkapolka** [comment]
Interesting, they are using this package https://www.npmjs.com/package/lighthouse you can try to get that to run in the codespace? just a thought

**Comment by benbobyabraham** [comment]
Was not able to run it using the codespace server because of the GitHub auth required. Will try out the method you suggested. @polkapolka

**Comment by benbobyabraham** [comment]
running lightroom over cli failed. @polkapolka , ill think i will just do this iteratively, if thats okay.

**Comment by polkapolka** [comment]
did the chrome extension fail as well?

**Comment by benbobyabraham** [comment]
The chrome extension only gives the score, not the underlying issues, so it is difficult to know what is to be fixed. Also i have noticed that score keeps changing on multiple attempts at analyzing, using the chrome extension.

**Comment by benbobyabraham** [comment]
Hi @polkapolka , could you verify and merge the pull request, so that i can work off another analysis.

**Comment by polkapolka** [comment]
Hi @benbobyabraham The reason your pr has merge conflicts is because you did not pull the commits that were merged into dev before continuing to work on the branch. I know it is confusing, but when i squash and merge, I create a new commit [68e682e](https://github.com/pybay/PyBay/commit/68e682e4e65fbb67c8869f1003fcd894166937d6) which is not the same as the individual commits that you submit because it is a combination of each individual commit. That means if you do not pull that commit back into your dev branch, then when you do another pr from the same branch, the commits are not the same and are flagged as in conflict when they are not in conflict.  I then have to do extra to merge.

**Comment by polkapolka** [comment]
@benbobyabraham merged and updated. Thanks. My advice is sync changes and start from a fresh codespace because the codespaces will sometimes say they are up to date with the repo changes and wont update with the latest changes.

**Comment by benbobyabraham** [comment]
@polkapolka noted. sorry about that. will do that from now on.

**Comment by polkapolka** [comment]
hey @benbobyabraham are you done experimenting with this or do you want to give this another try? lmk

**Comment by benbobyabraham** [comment]
Oh hey @polkapolka , i assumed since all the scores were above 90, I was waiting for you to assign me a new issue, or would you like me to continue working on it more. I'll keep working on the other issues that's listed if so. Thank you for the reaching out to me.

**Comment by polkapolka** [comment]
The diagnostic is still noticing stuff, so I would like you to keep knocking through the error messages if possible. 
https://pagespeed.web.dev/analysis/https-pybay-org/93t4b16t3m?form_factor=desktop
I merged your stuff so that you could get newer error messages.

**Comment by benbobyabraham** [comment]
Okay, sure, will do that, and update you @polkapolka

**Comment by polkapolka** [comment]
Thanks @benbobyabraham I am closing this issue.
