### ISSUE TITLE
Update workflow to create automatic deployment github action

### ISSUE THREAD

**Issue by polkapolka** [pybay/PyBay#3]
**Is your feature request related to a problem? Please describe.**
It is a feature that makes life easier.

**Describe the solution you'd like**
Github action

**Describe alternatives you've considered**
No

**Additional context**
NA

**Comment by benbobyabraham** [comment]
@polkapolka  would you like me to work on this?

**Comment by polkapolka** [comment]
No, this is a re-structure that I am working on.

**Comment by benbobyabraham** [comment]
Sounds good !!!
